CitasWeb/Citas.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Citas.Web.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

CitasWeb/Citas.Web/Controllers/PacientesController.cs
using Admon.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Citas.Web.Controllers
{
    public class PacientesController : Controller
    {
        // GET: Pacientes
        public ActionResult Index()
        {
            var pacientesBL = new PacientesBL();
            var listaPacientes = pacientesBL.ObtenerPaciente();

            return View(listaPacientes);
        }
    }
}

CitasWeb/Citas.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Bienvenidos al Hospital, le ayudaremos a reservar sus citas</h2>

CitasWeb/Citas.Web/Views/Pacientes/Index.cshtml
@model List<Admon.BL.Paciente>
@{
    ViewBag.Title = "Index";
}

<h2>Pacientes</h2>



<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                Codigo
            </th>
            <th>
                Nombre
            </th>
            <th>
                Direccion
            </th>

        </tr>
    </thead>

    @foreach (var paciente in Model)
    {
        <tr>
            <td>@paciente.Id</td>
            <td>@paciente.Nombre</td>
            <td>@paciente.Direccion</td>
            
        </tr>
    }
</table>

CitasWeb/Citas.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hospital", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Inicio", "Index", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Lista de Pacientes", "Index", "Pacientes")
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>